version: '3.8'

services:
  # 로그인 서버 (인증 서비스)
  auth-service:
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    ports:
      - "8001:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:password@postgres:5432/hospital_workers
      - REDIS_URL=redis://redis:6379
    depends_on:
      - postgres
      - redis
    networks:
      - hospital-network

  # API 서버 (비즈니스 로직)
  api-service:
    build:
      context: ./api-service
      dockerfile: Dockerfile
    ports:
      - "8002:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:password@postgres:5432/hospital_workers
      - REDIS_URL=redis://redis:6379
      - AUTH_SERVICE_URL=http://auth-service:8000
    depends_on:
      - postgres
      - redis
      - auth-service
    networks:
      - hospital-network

  # Nginx 리버스 프록시
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - auth-service
      - api-service
    networks:
      - hospital-network

  # PostgreSQL 데이터베이스
  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=hospital_workers
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - hospital-network

  # Redis 캐시/세션
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - hospital-network

volumes:
  postgres_data:

networks:
  hospital-network:
    driver: bridge
